sudo: false
language: python
python: 2.7
cache: pip
script: bash run-travis-tests.sh
before_deploy:
- openssl aes-256-cbc -K $encrypted_8a7b899f7bf7_key -iv $encrypted_8a7b899f7bf7_iv
  -in openfisca-bot.enc -out openfisca-bot -d
deploy:
- provider: script
  skip_cleanup: true
  script: ./release-tag.sh
  on:
    branch: master
- provider: pypi
  user: openfisca-bot
  password:
    secure: wSdQWuaukoAh6GeXdlLb0W//iEZKWIRbJjd3XIYAht4K9aI1iZZR2HhRW+VutI7Mm+FUhi71BkvWRgri3J8xaBmmcq8a/yce2dkkNCVc/W8pJnBRXec+S/eGdSeufeoBji1MCZBOF9jRN1l8aRPyBq5U56y9ly7T7GGrF9Dmp/A=
  distributions: bdist_wheel
  on:
    tags: true
